server:
  port: 8002
  servlet:
    context-path: /market-stock
spring:
  application:
    name: elysia-market-stock-service
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://${elysia.db.host}/elysia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${elysia.db.username}
    password: ${elysia.db.password}
  cloud:
    nacos:
      server-addr: ${elysia.nacos.host}
      discovery:
        username: ${elysia.nacos.username}
        password: ${elysia.nacos.password}
        namespace: public
        ephemeral: true #nacos注册服务提供方设置为非临时实例
#消费者微服务名称（Nacos服务名）
service-url:
  nacos-user-service: http://elysia-market-order-service
management:
  endpoint:
    web:
      exposure:
        include: '*'