server:
  port: 8080
spring:
  application:
    name: elysia-core
  profiles:
    active: local
  #####MYSQL CONNECT CONFIG#####
  datasource:
    url: jdbc:mysql://${elysia.db.host}/elysia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${elysia.db.pswd}
  #####REDIS CONNECT CONFIG#####
  redis:
    host: redis
    port: 6379
#    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间（负数表示没有限制）
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
      #连接超时时间
      timeout: 10000
